### ISSUE TITLE
Old Mearl - cannot access old impact indicator counts

### ISSUE THREAD

**Issue by sunehajagan** [Blue-Marine-Foundation/Maerl#122]
https://maerl-git-backup-old-maerl-blue-marine-foundation.vercel.app/impact : this link, once I sign in, first shows me an error page an then shows me the new Mearl page (and no count values for impact indicators) . Screenshots below, which also contain the URL: 
![Image](https://github.com/user-attachments/assets/eb231112-6205-4521-bf10-e6ae4c37a4fa)
![Image](https://github.com/user-attachments/assets/8691cc15-7325-4d42-b16a-ec29341abbc1)
![Image](https://github.com/user-attachments/assets/4b07fa73-6167-4ea2-a723-02025635e7c1)

**Comment by samjamead** [comment]
Ah yes, apologies, this is due to the way the authentication works and unfortunately we won't be able to fix this as technically old Maerl is on a different host... although I think there is a workaround: 

1. Log in to Maerl as normal (https://maerl.vercel.app/)
2. Go directly to the Impact page of old Maerl (https://maerl-git-backup-old-maerl-blue-marine-foundation.vercel.app/impact)

Let me know if this works for you!

**Comment by samjamead** [comment]
Hi @sunehajagan I have attached a CSV file with summaries of **valid** and **original** (i.e. removing duplicates) updates for each impact indicator. Hope this helps! 

[supabase_vqfxvjlhtmhqtwcpwddk_Impact Indicator Summary.csv](https://github.com/user-attachments/files/17935577/supabase_vqfxvjlhtmhqtwcpwddk_Impact.Indicator.Summary.csv)
